# Generated by Django 4.2.11 on 2024-04-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='select',
            field=models.CharField(default='.', max_length=100),
        ),
    ]
