# Generated by Django 4.2.11 on 2024-04-12 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_register_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='position',
            field=models.ForeignKey(default='.', on_delete=django.db.models.deletion.PROTECT, to='app.position'),
        ),
    ]
