# Generated by Django 4.2.11 on 2024-04-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_register_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_info',
            name='location',
            field=models.CharField(default='UZB', max_length=500),
        ),
    ]
